services:
    security.authentication.provider.loginza:
      class:  Zim32\LoginzaBundle\DependencyInjection\Security\LoginzaAuthenticationProvider
      arguments: [ @service_container, null ]
      abstract: true

    security.authentication.listener.loginza:
      class:  Zim32\LoginzaBundle\DependencyInjection\Security\LoginzaListener
      parent: security.authentication.listener.abstract
      abstract: true

    security.authentication.entry_point.loginza:
      class:  Zim32\LoginzaBundle\DependencyInjection\Security\LoginzaEntryPoint
      arguments: [@service_container]
